parameters:
    env(DATABASE_URL): ''

doctrine:
    dbal:
        driver: 'pdo_pgsql'
        server_version: '11'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Todo:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Todo/Infrastructure/Persistence/Doctrine/Mappings'
                prefix: 'Todo\Domain'