framework:
  messenger:
    transports:
      amqp: "%env(MESSENGER_TRANSPORT_DSN)%"

    # The bus that is going to be injected when injecting MessageBusInterface:
    default_bus: messenger.bus.commands

    # Create buses
    buses:
      messenger.bus.commands:
        middleware:
          - 'Shared\Infrastructure\Bus\Middleware\FinishesHandlingMessageBeforeHandlingNext'
      messenger.bus.events:
        default_middleware: allow_no_handlers

#    routing:
#      '*': amqp
