version: '2'
services:
  php:
    container_name: todo-php
    image: felixcarpena/php-swoole
    volumes:
      - ./:/app:cached
    ports:
      - "8080:9501"
    links:
      - db
      - rabbit
    command: php /app/public/index.php

  db:
    container_name: todo-db
    image: postgres:11
    environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=root
    - TERM=xterm
    ports:
    - "5432:5432"
    volumes:
    - ./postgres-data:/var/lib/postgresql/data

  rabbit:
    hostname: todo-rabbit
    container_name: todo-rabbit
    image: rabbitmq:3.7-management
    environment:
    - RABBITMQ_DEFAULT_USER=root
    - RABBITMQ_DEFAULT_PASS=root
    - VIRTUAL_HOST=/
    - VIRTUAL_PORT=15672
    ports:
    - "15672:15672"
    - "5672:5672"
