version: '2'
services:
  php:
    container_name: todo-php
    build: ./docker/php
    volumes:
      - ./:/app
    ports:
      - "8080:9501"
    links:
      - db
    networks:
      todo_net:
        ipv4_address: 172.16.238.2
    command: php /app/public/index.php

  db:
    container_name: todo-db
    image: postgres:11
    environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=root
    - TERM=xterm
    ports:
    - "5432:5432"
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    networks:
      todo_net:
        ipv4_address: 172.16.238.3

  rabbit:
    hostname: todo-rabbit
    container_name: todo-rabbit
    image: rabbitmq:3.7-management
    environment:
    - RABBITMQ_DEFAULT_USER=root
    - RABBITMQ_DEFAULT_PASS=root
    - VIRTUAL_HOST=/
    - VIRTUAL_PORT=15672
    ports:
    - "127.0.0.1::15672"
    - "127.0.0.1::5672"
    networks:
      todo_net:
        ipv4_address: 172.16.238.4
networks:
  todo_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
