parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Infrastructure\Ui\Http\:
        resource: '../src/Infrastructure/Ui/Http/'
        tags: ['controller.service_arguments']
